import { DOCUMENT } from '@angular/common';
import { computed, inject, Injectable, signal } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';

const EN_MESSAGES = {
  'document.title': 'MoneyTracker — Your money, in focus',
  'document.description': 'A calmer, clearer view of your money — day by day, month by month.',
  'language.select': 'Select language',
  'language.english': 'English',
  'language.vietnamese': 'Vietnamese',
  'brand.home': 'MoneyTracker home',
  'nav.main': 'Main navigation',
  'nav.mobile': 'Mobile navigation',
  'nav.transactions': 'Transactions',
  'nav.categories': 'Categories',
  'nav.reports': 'Report',
  'nav.wallets': 'Wallets',
  'nav.account': 'Account',
  'nav.soon': 'SOON',
  'nav.workspace': 'YOUR MONEY',
  'nav.tagline': 'A little more clarity, every day.',
  'nav.personalAccount': 'Personal account',
  'nav.signOut': 'Sign out',
  'nav.myAccount': 'My account',
  'auth.welcomeBack': 'WELCOME BACK',
  'auth.loginTitleFirst': 'Your money,',
  'auth.loginTitleSecond': 'all in one place.',
  'auth.loginDescription': 'Sign in to pick up where you left off.',
  'auth.email': 'Email address',
  'auth.emailPlaceholder': 'you@example.com',
  'auth.invalidEmail': 'Enter a valid email address.',
  'auth.password': 'Password',
  'auth.passwordPlaceholder': 'Your password',
  'auth.requiredPassword': 'Enter your password.',
  'auth.signingIn': 'Signing in…',
  'auth.signIn': 'Sign in',
  'auth.newToApp': 'New to MoneyTracker?',
  'auth.createAccount': 'Create an account',
  'auth.overview': 'MoneyTracker overview',
  'auth.focusTag': 'YOUR FINANCES, IN FOCUS',
  'auth.brandPromiseFirst': 'Make room',
  'auth.brandConnective': 'for',
  'auth.brandPromiseEmphasis': 'what matters.',
  'auth.brandDescription': 'A calmer, clearer view of your money — day by day, month by month.',
  'auth.smallSteps': 'Small steps add up.',
  'auth.brandFooter': 'A LITTLE MORE CLARITY, EVERY DAY.',
  'auth.freshStart': 'A FRESH START',
  'auth.registerTitleFirst': 'A clearer picture',
  'auth.registerTitleSecond': 'starts here.',
  'auth.registerDescription': 'Create your account. Your next good habit starts today.',
  'auth.name': 'Your name',
  'auth.namePlaceholder': 'How should we call you?',
  'auth.requiredName': 'Enter your name.',
  'auth.createPassword': 'Create a password',
  'auth.passwordLengthPlaceholder': 'At least 8 characters',
  'auth.passwordLengthError': 'Use a password between 8 and 128 characters.',
  'auth.creatingAccount': 'Creating account…',
  'auth.alreadyHaveAccount': 'Already have an account?',
  'auth.validEmail': 'Enter a valid email address.',
  'auth.createAccountAction': 'Create account',
  'auth.errorGeneric': 'Something went wrong. Please try again.',
  'auth.errorCredentials': 'That email and password combination was not recognized.',
  'auth.errorEmailTaken': 'An account with this email already exists. Try signing in instead.',
  'auth.errorValidation': 'Please check your details and try again.',
  'auth.errorOffline': 'Could not reach MoneyTracker. Check that the API is running.',
  'auth.errorRequest': 'We could not complete your request. Please try again.',
  'account.eyebrow': 'YOUR PROFILE',
  'account.title': 'Account',
  'account.subtitle': 'Manage your MoneyTracker sign-in.',
  'account.signOut': 'Sign out',
  'account.signOutDescription': 'Sign out of MoneyTracker on this device.',
  'account.signingOut': 'Signing out…',
  'account.logOut': 'Log out',
  'coming.eyebrow': 'COMING IN A LATER STAGE',
  'coming.categoriesTitle': 'Categories',
  'coming.categoriesDetail': 'Organize your spending and income with categories.',
  'coming.reportsTitle': 'Reports',
  'coming.reportsDetail': 'Explore a deeper breakdown of your finances.',
  'coming.accountTitle': 'Your account',
  'coming.accountDetail': 'Manage your profile and preferences.',
  'coming.transactionTitle': 'Add a transaction',
  'coming.transactionDetail': 'Transaction creation is coming in a later stage.',
  'coming.backToTransactions': 'Back to transactions',
  'transactions.walletFilters': 'Wallet and period filters',
  'transactions.selectWallet': 'Select a wallet',
  'transactions.allWallets': 'All wallets',
  'transactions.closeSearch': 'Close transaction search',
  'transactions.search': 'Search transactions',
  'transactions.periodOptions': 'Period options',
  'transactions.selectPeriod': 'Select period',
  'transactions.periodType': 'Period type',
  'transactions.searchPlaceholder': 'Search notes, categories, amounts…',
  'transactions.clearSearch': 'Clear search',
  'transactions.openingBalance': 'Opening balance',
  'transactions.choosePeriod': 'Choose period',
  'transactions.summaryAndList':
    'Period summary and transactions. Swipe left or right to change period.',
  'transactions.viewReport': 'View report for this period',
  'transactions.inflow': 'Inflow',
  'transactions.outflow': 'Outflow',
  'transactions.net': 'Net',
  'transactions.transaction': 'transaction',
  'transactions.transactions': 'transactions',
  'transactions.loadFailureTitle': 'Transactions couldn’t load',
  'transactions.tryAgain': 'Try again',
  'transactions.loading': 'Loading transactions',
  'transactions.noMatches': 'No matching transactions',
  'transactions.nothingThisPeriod': 'Nothing recorded this period',
  'transactions.tryDifferentSearch': 'Try a different search or clear the filter.',
  'transactions.periodWillAppear': 'Your transactions for this period will appear here.',
  'transactions.jumpCurrent': 'Jump to current period',
  'transactions.future': 'Future',
  'transactions.futureAccessible': 'Future period, all time after the current period',
  'transactions.categoryFallback': 'Other',
  'transactions.walletFallback': 'Personal',
  'transactions.errorOffline':
    'Could not reach the API. Make sure it is running on localhost:5100.',
  'transactions.errorLoad': 'Your transactions could not be loaded. Please try again.',
  'wallets.eyebrow': 'YOUR MONEY',
  'wallets.title': 'Wallets',
  'wallets.subtitle': 'Manage the accounts you use to track your money.',
  'wallets.add': 'Add wallet',
  'wallets.edit': 'Edit',
  'wallets.delete': 'Delete',
  'wallets.cancel': 'Cancel',
  'wallets.save': 'Save wallet',
  'wallets.saving': 'Saving…',
  'wallets.name': 'Wallet name',
  'wallets.namePlaceholder': 'e.g. Everyday account',
  'wallets.nameRequired': 'Enter a wallet name.',
  'wallets.type': 'Wallet type',
  'wallets.regular': 'Regular',
  'wallets.credit': 'Credit',
  'wallets.currency': 'Currency',
  'wallets.currencyPlaceholder': 'VND',
  'wallets.currencyRequired': 'Enter a currency code.',
  'wallets.openingBalance': 'Opening balance',
  'wallets.creditLimit': 'Credit limit',
  'wallets.icon': 'Icon (optional)',
  'wallets.color': 'Color (optional)',
  'wallets.regularDescription': 'Regular wallet',
  'wallets.creditDescription': 'Credit wallet',
  'wallets.openingBalanceSummary': 'Opening balance',
  'wallets.creditLimitSummary': 'Credit limit',
  'wallets.emptyTitle': 'No wallets yet',
  'wallets.emptyDescription': 'Add a wallet to start organizing your money.',
  'wallets.loadError': 'Your wallets could not be loaded. Please try again.',
  'wallets.offlineError': 'Could not reach MoneyTracker. Check that the API is running.',
  'wallets.saveError': 'The wallet could not be saved. Please try again.',
  'wallets.deleteError': 'The wallet could not be deleted. Please try again.',
  'wallets.invalidCreditLimit': 'Enter a credit limit greater than zero.',
  'wallets.duplicateId': 'This wallet already exists. Refresh the list and try again.',
  'wallets.notFound': 'This wallet is no longer available. Refresh the list and try again.',
  'wallets.deletePrompt': 'Delete this wallet? Its transaction history will be preserved.',
  'wallets.confirmDelete': 'Delete wallet',
  'wallets.deleting': 'Deleting…',
  'wallets.loadRetry': 'Try again',
  'period.today': 'Today',
  'period.yesterday': 'Yesterday',
  'period.day': 'day',
  'period.week': 'week',
  'period.month': 'month',
  'period.year': 'year',
  'period.typeDay': 'Day',
  'period.typeWeek': 'Week',
  'period.typeMonth': 'Month',
  'period.typeQuarter': 'Quarter',
  'period.typeYear': 'Year',
  'period.this': 'This {period}',
  'period.last': 'Last {period}',
  'period.quarter': 'Q{quarter} {year}',
  'period.navigationQuarter': '{quarter}-{year}',
} as const;

export type TranslationKey = keyof typeof EN_MESSAGES;

const VI_MESSAGES: Record<TranslationKey, string> = {
  'language.select': 'Chọn ngôn ngữ',
  'document.title': 'MoneyTracker — Tài chính của bạn, rõ ràng hơn',
  'document.description': 'Theo dõi tài chính nhẹ nhàng, rõ ràng hơn — từng ngày, từng tháng.',
  'language.english': 'Tiếng Anh',
  'language.vietnamese': 'Tiếng Việt',
  'brand.home': 'Trang chủ MoneyTracker',
  'nav.main': 'Điều hướng chính',
  'nav.mobile': 'Điều hướng trên thiết bị di động',
  'nav.transactions': 'Giao dịch',
  'nav.categories': 'Danh mục',
  'nav.reports': 'Báo cáo',
  'nav.wallets': 'Ví',
  'nav.account': 'Tài khoản',
  'nav.soon': 'SẮP RA MẮT',
  'nav.workspace': 'TÀI CHÍNH CỦA BẠN',
  'nav.tagline': 'Mỗi ngày, tài chính thêm rõ ràng.',
  'nav.personalAccount': 'Tài khoản cá nhân',
  'nav.signOut': 'Đăng xuất',
  'nav.myAccount': 'Tài khoản của tôi',
  'auth.welcomeBack': 'CHÀO MỪNG BẠN TRỞ LẠI',
  'auth.loginTitleFirst': 'Tài chính của bạn,',
  'auth.loginTitleSecond': 'gói gọn trong một nơi.',
  'auth.loginDescription': 'Đăng nhập để tiếp tục sử dụng.',
  'auth.email': 'Địa chỉ email',
  'auth.emailPlaceholder': 'ban@example.com',
  'auth.invalidEmail': 'Vui lòng nhập địa chỉ email hợp lệ.',
  'auth.password': 'Mật khẩu',
  'auth.passwordPlaceholder': 'Mật khẩu của bạn',
  'auth.requiredPassword': 'Vui lòng nhập mật khẩu.',
  'auth.signingIn': 'Đang đăng nhập…',
  'auth.signIn': 'Đăng nhập',
  'auth.newToApp': 'Bạn mới dùng MoneyTracker?',
  'auth.createAccount': 'Tạo tài khoản',
  'auth.overview': 'Giới thiệu MoneyTracker',
  'auth.focusTag': 'TẬP TRUNG VÀO TÀI CHÍNH CỦA BẠN',
  'auth.brandPromiseFirst': 'Dành chỗ',
  'auth.brandConnective': 'cho',
  'auth.brandPromiseEmphasis': 'điều quan trọng.',
  'auth.brandDescription': 'Theo dõi tài chính nhẹ nhàng, rõ ràng hơn — từng ngày, từng tháng.',
  'auth.smallSteps': 'Từng bước nhỏ tạo nên thay đổi lớn.',
  'auth.brandFooter': 'MỖI NGÀY, TÀI CHÍNH THÊM RÕ RÀNG.',
  'auth.freshStart': 'BẮT ĐẦU MỚI',
  'auth.registerTitleFirst': 'Bức tranh tài chính rõ ràng',
  'auth.registerTitleSecond': 'bắt đầu từ đây.',
  'auth.registerDescription': 'Tạo tài khoản để bắt đầu xây dựng thói quen tài chính tốt.',
  'auth.name': 'Tên của bạn',
  'auth.namePlaceholder': 'Chúng tôi nên gọi bạn là gì?',
  'auth.requiredName': 'Vui lòng nhập tên.',
  'auth.createPassword': 'Tạo mật khẩu',
  'auth.passwordLengthPlaceholder': 'Ít nhất 8 ký tự',
  'auth.passwordLengthError': 'Mật khẩu cần có từ 8 đến 128 ký tự.',
  'auth.creatingAccount': 'Đang tạo tài khoản…',
  'auth.alreadyHaveAccount': 'Bạn đã có tài khoản?',
  'auth.validEmail': 'Vui lòng nhập địa chỉ email hợp lệ.',
  'auth.createAccountAction': 'Tạo tài khoản',
  'auth.errorGeneric': 'Đã xảy ra lỗi. Vui lòng thử lại.',
  'auth.errorCredentials': 'Email hoặc mật khẩu không chính xác.',
  'auth.errorEmailTaken': 'Email này đã được đăng ký. Hãy thử đăng nhập.',
  'auth.errorValidation': 'Vui lòng kiểm tra thông tin và thử lại.',
  'auth.errorOffline': 'Không thể kết nối MoneyTracker. Hãy kiểm tra API đang chạy.',
  'auth.errorRequest': 'Không thể hoàn tất yêu cầu. Vui lòng thử lại.',
  'account.eyebrow': 'HỒ SƠ CỦA BẠN',
  'account.title': 'Tài khoản',
  'account.subtitle': 'Quản lý thông tin đăng nhập MoneyTracker.',
  'account.signOut': 'Đăng xuất',
  'account.signOutDescription': 'Đăng xuất MoneyTracker trên thiết bị này.',
  'account.signingOut': 'Đang đăng xuất…',
  'account.logOut': 'Đăng xuất',
  'coming.eyebrow': 'SẼ CÓ TRONG GIAI ĐOẠN TIẾP THEO',
  'coming.categoriesTitle': 'Danh mục',
  'coming.categoriesDetail': 'Sắp xếp các khoản thu chi theo danh mục.',
  'coming.reportsTitle': 'Báo cáo',
  'coming.reportsDetail': 'Xem phân tích chi tiết hơn về tình hình tài chính.',
  'coming.accountTitle': 'Tài khoản của bạn',
  'coming.accountDetail': 'Quản lý hồ sơ và tùy chọn của bạn.',
  'coming.transactionTitle': 'Thêm giao dịch',
  'coming.transactionDetail': 'Tính năng tạo giao dịch sẽ có trong giai đoạn tiếp theo.',
  'coming.backToTransactions': 'Quay lại giao dịch',
  'transactions.walletFilters': 'Bộ lọc ví và kỳ',
  'transactions.selectWallet': 'Chọn ví',
  'transactions.allWallets': 'Tất cả ví',
  'transactions.closeSearch': 'Đóng tìm kiếm giao dịch',
  'transactions.search': 'Tìm kiếm giao dịch',
  'transactions.periodOptions': 'Tùy chọn kỳ',
  'transactions.selectPeriod': 'Chọn kỳ',
  'transactions.periodType': 'Loại kỳ',
  'transactions.searchPlaceholder': 'Tìm ghi chú, danh mục, số tiền…',
  'transactions.clearSearch': 'Xóa tìm kiếm',
  'transactions.openingBalance': 'Số dư đầu kỳ',
  'transactions.choosePeriod': 'Chọn kỳ',
  'transactions.summaryAndList':
    'Tổng quan và danh sách giao dịch trong kỳ. Vuốt sang trái hoặc phải để đổi kỳ.',
  'transactions.viewReport': 'Xem báo cáo kỳ này',
  'transactions.inflow': 'Tiền vào',
  'transactions.outflow': 'Tiền ra',
  'transactions.net': 'Chênh lệch',
  'transactions.transaction': 'giao dịch',
  'transactions.transactions': 'giao dịch',
  'transactions.loadFailureTitle': 'Không thể tải giao dịch',
  'transactions.tryAgain': 'Thử lại',
  'transactions.loading': 'Đang tải giao dịch',
  'transactions.noMatches': 'Không tìm thấy giao dịch phù hợp',
  'transactions.nothingThisPeriod': 'Chưa có giao dịch trong kỳ này',
  'transactions.tryDifferentSearch': 'Hãy thử từ khóa khác hoặc xóa bộ lọc.',
  'transactions.periodWillAppear': 'Giao dịch trong kỳ này sẽ hiển thị tại đây.',
  'transactions.jumpCurrent': 'Đến kỳ hiện tại',
  'transactions.future': 'Tương lai',
  'transactions.futureAccessible': 'Kỳ tương lai, bao gồm thời gian sau kỳ hiện tại',
  'transactions.categoryFallback': 'Khác',
  'transactions.walletFallback': 'Cá nhân',
  'transactions.errorOffline':
    'Không thể kết nối API. Hãy kiểm tra API đang chạy tại localhost:5100.',
  'transactions.errorLoad': 'Không thể tải giao dịch. Vui lòng thử lại.',
  'wallets.eyebrow': 'TÀI CHÍNH CỦA BẠN',
  'wallets.title': 'Ví',
  'wallets.subtitle': 'Quản lý các tài khoản bạn dùng để theo dõi tiền.',
  'wallets.add': 'Thêm ví',
  'wallets.edit': 'Chỉnh sửa',
  'wallets.delete': 'Xóa',
  'wallets.cancel': 'Hủy',
  'wallets.save': 'Lưu ví',
  'wallets.saving': 'Đang lưu…',
  'wallets.name': 'Tên ví',
  'wallets.namePlaceholder': 'Ví dụ: Tài khoản chi tiêu',
  'wallets.nameRequired': 'Vui lòng nhập tên ví.',
  'wallets.type': 'Loại ví',
  'wallets.regular': 'Thông thường',
  'wallets.credit': 'Tín dụng',
  'wallets.currency': 'Tiền tệ',
  'wallets.currencyPlaceholder': 'VND',
  'wallets.currencyRequired': 'Vui lòng nhập mã tiền tệ.',
  'wallets.openingBalance': 'Số dư ban đầu',
  'wallets.creditLimit': 'Hạn mức tín dụng',
  'wallets.icon': 'Biểu tượng (không bắt buộc)',
  'wallets.color': 'Màu sắc (không bắt buộc)',
  'wallets.regularDescription': 'Ví thông thường',
  'wallets.creditDescription': 'Ví tín dụng',
  'wallets.openingBalanceSummary': 'Số dư ban đầu',
  'wallets.creditLimitSummary': 'Hạn mức tín dụng',
  'wallets.emptyTitle': 'Chưa có ví nào',
  'wallets.emptyDescription': 'Thêm ví để bắt đầu quản lý tiền của bạn.',
  'wallets.loadError': 'Không thể tải danh sách ví. Vui lòng thử lại.',
  'wallets.offlineError': 'Không thể kết nối MoneyTracker. Hãy kiểm tra API đang chạy.',
  'wallets.saveError': 'Không thể lưu ví. Vui lòng thử lại.',
  'wallets.deleteError': 'Không thể xóa ví. Vui lòng thử lại.',
  'wallets.invalidCreditLimit': 'Vui lòng nhập hạn mức tín dụng lớn hơn 0.',
  'wallets.duplicateId': 'Ví này đã tồn tại. Hãy tải lại danh sách và thử lại.',
  'wallets.notFound': 'Ví này không còn tồn tại. Hãy tải lại danh sách và thử lại.',
  'wallets.deletePrompt': 'Xóa ví này? Lịch sử giao dịch của ví sẽ được giữ lại.',
  'wallets.confirmDelete': 'Xóa ví',
  'wallets.deleting': 'Đang xóa…',
  'wallets.loadRetry': 'Thử lại',
  'period.today': 'Hôm nay',
  'period.yesterday': 'Hôm qua',
  'period.day': 'ngày',
  'period.week': 'tuần',
  'period.month': 'tháng',
  'period.year': 'năm',
  'period.typeDay': 'Ngày',
  'period.typeWeek': 'Tuần',
  'period.typeMonth': 'Tháng',
  'period.typeQuarter': 'Quý',
  'period.typeYear': 'Năm',
  'period.this': '{period} này',
  'period.last': '{period} trước',
  'period.quarter': 'Quý {quarter} năm {year}',
  'period.navigationQuarter': 'Quý {quarter} năm {year}',
};

export type Language = 'en' | 'vi';

const LANGUAGE_STORAGE_KEY = 'money-tracker.language';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly document = inject(DOCUMENT);
  private readonly title = inject(Title);
  private readonly meta = inject(Meta);
  readonly language = signal<Language>(this.getInitialLanguage());
  readonly locale = computed(() => (this.language() === 'vi' ? 'vi-VN' : 'en-US'));

  constructor() {
    this.updateDocumentLanguage();
  }

  setLanguage(language: Language): void {
    this.language.set(language);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    this.updateDocumentLanguage();
  }

  t(key: TranslationKey, params: Record<string, string | number> = {}): string {
    const messages = this.language() === 'vi' ? VI_MESSAGES : EN_MESSAGES;
    return Object.entries(params).reduce(
      (message, [name, value]) => message.replaceAll(`{${name}}`, String(value)),
      messages[key],
    );
  }

  private getInitialLanguage(): Language {
    const savedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (savedLanguage === 'en' || savedLanguage === 'vi') return savedLanguage;
    return navigator.language.toLowerCase().startsWith('vi') ? 'vi' : 'en';
  }

  private updateDocumentLanguage(): void {
    this.document.documentElement.lang = this.language() === 'vi' ? 'vi' : 'en';
    this.title.setTitle(this.t('document.title'));
    this.meta.updateTag({ name: 'description', content: this.t('document.description') });
  }
}
